import React from 'react';
import { motion as Motion } from 'framer-motion';
import { Crown, ShieldCheck, Sparkles } from 'lucide-react';
import { useLocale } from '../lib/i18n.js';
import './About.css';

const fadeIn = { initial: { opacity: 1, y: 0 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6, ease: [0.16, 1, 0.3, 1] } };
const staggerContainer = { animate: { transition: { staggerChildren: 0.1 } } };
const copyFor = (locale) => locale === 'en' ? {
  eyebrow: 'The studio essence', titlePrefix: 'Our', titleAccent: 'Story', lead: 'Discover the vision, passion and commitment that inspire Golden Studio Plus every day.', origins: 'Origins', historyTitle: 'A passion for visual excellence', historyOne: 'Located in the heart of Douala, Cameroon, Golden Studio Plus was born from a deep passion for visual art and the desire to capture pure elegance. Our mission is to preserve your most precious moments through a professional lens while offering a truly unique Afro-Luxe experience.', historyTwo: 'We push beyond conventional photography to elevate your memories with a distinctive touch, combining creativity, technological innovation and attention to detail. Every session is designed to reveal your natural, authentic radiance.', quote: 'More than you imagined!', motto: 'Our motto', imageAlt: 'Professional photo session at Golden Studio Plus', commitments: 'Our commitments', why: 'Why choose us?', excellence: 'Excellence', excellenceText: 'We deliver high-definition photographs, carefully retouched for a lasting and impeccable result.', premium: 'Premium setting', premiumText: 'A studio designed for your comfort, with professional equipment.', privacy: 'Privacy', privacyText: 'Your data and visuals are handled in accordance with the privacy commitments presented on the website.',
} : {
  eyebrow: 'L’essence du studio', titlePrefix: 'Notre', titleAccent: 'Histoire', lead: 'Découvrez la vision, la passion et l’engagement qui animent Golden Studio Plus chaque jour.', origins: 'Origines', historyTitle: 'Une passion pour l’excellence visuelle', historyOne: 'Situé au cœur de Douala au Cameroun, Golden Studio Plus est né d’une passion ardente pour l’art visuel et le besoin de capturer l’élégance à l’état pur. Notre mission est d’immortaliser vos instants les plus précieux à travers un objectif professionnel, tout en offrant une expérience « Afro-Luxe » unique en son genre.', historyTwo: 'Nous repoussons les limites de la photographie classique pour sublimer vos souvenirs avec une touche divine, en conjuguant créativité, innovation technologique et perfectionnisme. Chaque séance est pensée pour révéler votre éclat naturel et authentique.', quote: 'Plus que vous ne l’avez imaginé !', motto: 'Notre devise', imageAlt: 'Séance photo professionnelle au Golden Studio Plus', commitments: 'Nos engagements', why: 'Pourquoi nous choisir ?', excellence: 'Excellence', excellenceText: 'Nous livrons des photos en haute définition retouchées avec minutie, pour un rendu impeccable qui traverse le temps.', premium: 'Cadre Premium', premiumText: 'Un studio conçu pour votre confort, avec un équipement professionnel.', privacy: 'Confidentialité', privacyText: 'Vos données et vos visuels sont traités conformément aux engagements de confidentialité présentés sur le site.',
};

const About = () => {
  const { locale } = useLocale();
  const copy = copyFor(locale);
  return <div className="about-page">
    <section className="about-hero" aria-labelledby="about-title"><div className="about-hero__bg" /><div className="container about-hero__content"><Motion.div initial={{ opacity: 0, y: 30 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.8 }}><p className="about-eyebrow"><Sparkles size={16} className="text-gold" />{copy.eyebrow}</p><h1 id="about-title" className="hero-title">{copy.titlePrefix} <span className="text-gold">{copy.titleAccent}</span></h1><p className="about-hero__lead">{copy.lead}</p></Motion.div></div></section>
    <section className="about-history py-section"><div className="container"><div className="history-layout"><Motion.div className="history-content" initial="initial" whileInView="animate" viewport={{ once: true, margin: '-100px' }} variants={staggerContainer}><Motion.p className="home-section-label" variants={fadeIn}>{copy.origins}</Motion.p><Motion.h2 variants={fadeIn}>{copy.historyTitle}</Motion.h2><Motion.div className="heading-separator" variants={fadeIn} /><Motion.p variants={fadeIn}>{copy.historyOne}</Motion.p><Motion.p variants={fadeIn}>{copy.historyTwo}</Motion.p><Motion.div className="history-quote" variants={fadeIn}><p>“{copy.quote}”</p><span>{copy.motto}</span></Motion.div></Motion.div><Motion.div className="history-image-wrap" initial={{ opacity: 1, scale: 1 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ duration: 0.8, ease: 'easeOut' }}><img src="/images/optimized/about-studio-640.webp" srcSet="/images/optimized/about-studio-640.webp 640w, /images/optimized/about-studio-1024.webp 1024w" sizes="(max-width: 800px) 100vw, 50vw" width="640" height="640" alt={copy.imageAlt} loading="lazy" decoding="async" /></Motion.div></div></div></section>
    <section className="about-values py-section bg-dark text-on-dark"><div className="container"><Motion.div className="home-section-heading center" initial="initial" whileInView="animate" viewport={{ once: true }} variants={fadeIn}><p className="home-section-label">{copy.commitments}</p><h2 style={{ color: '#fff' }}>{copy.why}</h2><div className="heading-separator" style={{ margin: '1.5rem auto' }} /></Motion.div><Motion.div className="values-grid" initial="initial" whileInView="animate" viewport={{ once: true }} variants={staggerContainer}><Motion.div className="value-card glass-dark" variants={fadeIn}><div className="value-icon"><Crown size={32} /></div><h3>{copy.excellence}</h3><p>{copy.excellenceText}</p></Motion.div><Motion.div className="value-card glass-dark" variants={fadeIn}><div className="value-icon"><Sparkles size={32} /></div><h3>{copy.premium}</h3><p>{copy.premiumText}</p></Motion.div><Motion.div className="value-card glass-dark" variants={fadeIn}><div className="value-icon"><ShieldCheck size={32} /></div><h3>{copy.privacy}</h3><p>{copy.privacyText}</p></Motion.div></Motion.div></div></section>
  </div>;
};

export default About;
