import { createElement, useEffect, useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import { motion as Motion } from 'framer-motion';
import { ArrowRight, BriefcaseBusiness, CalendarCheck, Camera, CheckCircle2, Clock3, Images, Palette, Sparkles, Star, Users } from 'lucide-react';
import { getPackages } from '../lib/api';
import { packageView } from '../lib/packages';
import { useLocale } from '../lib/i18n.js';
import './Home.css';

const fadeIn = { initial: { opacity: 1, y: 0 }, animate: { opacity: 1, y: 0 }, transition: { duration: 0.6, ease: [0.16, 1, 0.3, 1] } };
const staggerContainer = { animate: { transition: { staggerChildren: 0.1 } } };
const popularPackSlugs = ['classic-propre', 'pack-signature', 'duo-couple'];
const popularPackFallback = [
  { id: 'classic-propre', slug: 'classic-propre', name: 'Classic Propre', category: 'Portraits & identité', price: 18_000, durationMin: 60, deliveryLabel: 'Livraison sous 48 à 72 heures', bookingMode: 'DIRECT' },
  { id: 'pack-signature', slug: 'pack-signature', name: 'Signature', category: 'Portraits & identité', price: 32_000, durationMin: 90, bookingMode: 'DIRECT' },
  { id: 'duo-couple', slug: 'duo-couple', name: 'Duo & Couple', category: 'Couples, familles & groupes', price: 22_000, durationMin: 60, bookingMode: 'DIRECT' },
];
const visualPaths = [
  { icon: Camera, image: '/images/optimized/portfolio-portrait-2-1024.webp', imageSmall: '/images/optimized/portfolio-portrait-2-480.webp', imagePosition: 'center top', to: '/services' },
  { icon: BriefcaseBusiness, image: '/images/optimized/portfolio-corporate-1024.webp', imageSmall: '/images/optimized/portfolio-corporate-480.webp', imagePosition: 'center top', to: '/corporate' },
  { icon: Palette, image: '/images/optimized/engagement-1024.webp', imageSmall: '/images/optimized/engagement-480.webp', imagePosition: 'center top', to: '/services-creatifs' },
];
const visualPortfolio = [
  { src: '/images/optimized/portfolio-portrait-2-1024.webp', srcSmall: '/images/optimized/portfolio-portrait-2-480.webp', className: 'portfolio-large', objectPosition: 'center top' },
  { src: '/images/optimized/portfolio-couple-1024.webp', srcSmall: '/images/optimized/portfolio-couple-480.webp', objectPosition: 'center top' },
  { src: '/images/optimized/portfolio-maternity-1024.webp', srcSmall: '/images/optimized/portfolio-maternity-480.webp', objectPosition: 'center top' },
  { src: '/images/optimized/portfolio-corporate-1024.webp', srcSmall: '/images/optimized/portfolio-corporate-480.webp', objectPosition: 'center top' },
];

const copyFor = (locale) => locale === 'en' ? {
  imageAlt: 'Portrait photographed in the Golden Studio Plus studio', eyebrow: 'PHOTOGRAPHIC EXCELLENCE IN DOUALA', heroPrefix: 'Reveal your', heroAccent: 'radiance', heroJoin: 'with', heroLead: 'Premium portraits, exceptional memories and corporate visuals designed to make an impression.', reserve: 'Book my session', explore: 'Explore our packages', proof: [{ value: '48h', label: 'retouched delivery' }, { value: '22', label: 'studio packages' }, { value: '4K', label: 'high-definition finish' }], universes: 'Our worlds', experience: 'An immersive, guided experience', services: [{ title: 'Photo sessions', text: 'Portraits, families, maternity and events.' }, { title: 'Corporate imagery', text: 'LinkedIn portraits and company content.' }, { title: 'Design & printing', text: 'Retouching, albums and personalised products.' }], offers: 'Current offers', packs: 'Signature packages', essential: 'Essential', delivery: 'Delivery:', bookNow: 'Book now', details: { 'classic-propre': ['Individual portrait', 'Retouching included', 'Ideal for a professional profile'], 'pack-signature': ['Editorial direction', 'Premium finish', 'More variations'], 'duo-couple': ['Session for two', 'Pose guidance', 'Natural atmosphere'] }, portfolioTitle: 'The art of capturing the moment', portfolioText: 'Every session is a unique work. We shape light and composition to create images that tell your story with elegance.', viewGallery: 'Explore the gallery', portfolioLabels: ['Studio portrait', 'Couple session', 'Maternity', 'Corporate'], testimonialsLabel: 'Testimonials', testimonialsTitle: 'They trusted us', testimonials: [{ quote: 'A very professional studio. I received my photos quickly and the quality was truly there.', name: 'Nadège M.', context: 'Studio portrait' }, { quote: 'The welcome was warm. The Duo package was perfect for us, with a very natural result.', name: 'Christelle & Paul', context: 'Couple session' }, { quote: 'Beautiful corporate portraits for our entire team. The finish is polished and consistent.', name: 'Dieudonné K.', context: 'Corporate' }], finalTitle: 'Ready for an unforgettable experience?', finalText: 'Book your time slot in just a few clicks and let the magic happen.', finalAction: 'Start the journey',
} : {
  imageAlt: 'Portrait réalisé en studio par Golden Studio Plus', eyebrow: 'L’EXCELLENCE PHOTOGRAPHIQUE À DOUALA', heroPrefix: 'Révélez votre', heroAccent: 'éclat', heroJoin: 'avec', heroLead: 'Portraits premium, souvenirs d’exception et visuels corporate conçus pour marquer les esprits.', reserve: 'Réserver ma séance', explore: 'Explorer nos packs', proof: [{ value: '48h', label: 'livraison retouchée' }, { value: '22', label: 'packs studio' }, { value: '4K', label: 'rendu haute définition' }], universes: 'Nos Univers', experience: 'Une expérience immersive & guidée', services: [{ title: 'Séances photo', text: 'Portraits, familles, maternité et événementiel.' }, { title: 'Image corporate', text: 'Portraits LinkedIn et contenus d’entreprise.' }, { title: 'Design & impression', text: 'Retouches, albums et produits personnalisés.' }], offers: 'Offres du Moment', packs: 'Packs Signature', essential: 'Incontournable', delivery: 'Livraison :', bookNow: 'Réserver maintenant', details: { 'classic-propre': ['Portrait individuel', 'Retouche incluse', 'Idéal pour un profil professionnel'], 'pack-signature': ['Direction éditoriale', 'Rendu premium', 'Plus de variations'], 'duo-couple': ['Séance à deux', 'Guidage des poses', 'Ambiance naturelle'] }, portfolioTitle: 'L’art de capturer l’instant', portfolioText: 'Chaque séance est une œuvre unique. Nous travaillons la lumière et la composition pour créer des images qui racontent votre histoire avec élégance.', viewGallery: 'Découvrir la galerie', portfolioLabels: ['Portrait studio', 'Séance couple', 'Maternité', 'Corporate'], testimonialsLabel: 'Témoignages', testimonialsTitle: 'Ils nous ont fait confiance', testimonials: [{ quote: 'Studio hyper pro, j’ai eu mes photos rapidement et la qualité est vraiment au rendez-vous.', name: 'Nadège M.', context: 'Portrait studio' }, { quote: 'L’accueil est chaleureux. Le pack Duo était parfait pour nous, avec un résultat très naturel.', name: 'Christelle & Paul', context: 'Séance couple' }, { quote: 'Des portraits corporate magnifiques pour toute notre équipe. Le rendu est propre et cohérent.', name: 'Dieudonné K.', context: 'Corporate' }], finalTitle: 'Prêt pour une expérience inoubliable ?', finalText: 'Réservez votre créneau en quelques clics et laissez la magie opérer.', finalAction: 'Démarrer l’aventure',
};

const Home = () => {
  const { locale } = useLocale();
  const copy = useMemo(() => copyFor(locale), [locale]);
  const [popularPacks, setPopularPacks] = useState([]);
  useEffect(() => { let isMounted = true; const present = (items) => { if (!isMounted) return; const normalized = items.map((item) => packageView(item, locale)); const selected = popularPackSlugs.map((slug) => normalized.find((pack) => pack.slug === slug)).filter(Boolean).map((pack) => ({ ...pack, details: copy.details[pack.slug] || [], featured: pack.slug === 'pack-signature' })); if (selected.length) setPopularPacks(selected); }; present(popularPackFallback); getPackages().then(present).catch(() => {}); return () => { isMounted = false; }; }, [copy.details, locale]);
  const services = visualPaths.map((item, index) => ({ ...item, ...copy.services[index] }));
  const previews = visualPortfolio.map((item, index) => ({ ...item, label: copy.portfolioLabels[index] }));
  return <div className="home">
    <section className="home-hero" aria-labelledby="home-hero-title"><Motion.div className="home-hero__bg" initial={{ scale: 1.1, opacity: 0 }} animate={{ scale: 1, opacity: 1 }} transition={{ duration: 1.5, ease: 'easeOut' }}><img src="/images/optimized/hero-banner-1024.webp" srcSet="/images/optimized/hero-banner-640.webp 640w, /images/optimized/hero-banner-1024.webp 1024w" sizes="100vw" width="1024" height="1024" alt={copy.imageAlt} className="home-hero__image" fetchPriority="high" decoding="async" /><div className="home-hero__overlay" /></Motion.div><div className="container home-hero__content"><Motion.div className="home-hero__copy" initial={{ opacity: 0, x: -30 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.8, delay: 0.5 }}><p className="home-eyebrow"><Sparkles size={16} className="text-gold" />{copy.eyebrow}</p><h1 id="home-hero-title" className="hero-title">{copy.heroPrefix} <span className="text-gold">{copy.heroAccent}</span> {copy.heroJoin} Golden Studio Plus.</h1><p className="home-hero__lead">{copy.heroLead}</p><div className="home-hero__actions"><Link to="/reservation" className="btn btn-primary"><CalendarCheck size={19} />{copy.reserve}</Link><Link to="/services" className="btn btn-secondary glass">{copy.explore}</Link></div><div className="home-hero__proof">{copy.proof.map((item, index) => <Motion.div key={item.label} className="home-proof-item" initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1 + index * 0.1 }}><strong className="text-gold">{item.value}</strong><span>{item.label}</span></Motion.div>)}</div></Motion.div></div></section>
    <section className="home-section home-services py-section" aria-labelledby="services-title"><div className="container"><Motion.div className="home-section-heading center" initial="initial" whileInView="animate" viewport={{ once: true }} variants={fadeIn}><p className="home-section-label">{copy.universes}</p><h2 id="services-title">{copy.experience}</h2><div className="heading-separator" /></Motion.div><Motion.div className="home-service-grid" initial="initial" whileInView="animate" viewport={{ once: true }} variants={staggerContainer}>{services.map(({ icon: Icon, title, text, image, imageSmall, imagePosition, to }) => <Motion.div key={title} variants={fadeIn}><Link className="home-service-card" to={to}><div className="service-card__image-wrap" style={{ '--service-image-position': imagePosition }}><img src={imageSmall} srcSet={`${imageSmall} 480w, ${image} 1024w`} sizes="(max-width: 760px) 100vw, 33vw" width="480" height="480" alt="" aria-hidden="true" loading="lazy" decoding="async" /><div className="service-card__overlay" /></div><div className="home-service-card__content"><div className="service-card__heading"><div className="service-card__icon">{createElement(Icon, { size: 24, 'aria-hidden': true })}</div><h3>{title}</h3></div><div className="service-card__text"><p>{text}</p></div><div className="service-card__arrow"><ArrowRight size={20} /></div></div></Link></Motion.div>)}</Motion.div></div></section>
    <section className="home-section home-packs py-section bg-cream" aria-labelledby="packs-title"><div className="container"><Motion.div className="home-section-heading center" initial="initial" whileInView="animate" viewport={{ once: true }} variants={fadeIn}><p className="home-section-label">{copy.offers}</p><h2 id="packs-title">{copy.packs}</h2></Motion.div><Motion.div className="home-pack-grid" initial="initial" whileInView="animate" viewport={{ once: true }} variants={staggerContainer}>{popularPacks.map((pack) => <Motion.article className={`home-pack-card ${pack.featured ? 'is-featured' : ''} glass`} key={pack.id} variants={fadeIn}>{pack.featured && <div className="home-pack-badge">{copy.essential}</div>}<div className="pack-card__header"><h3>{pack.name}</h3><div className="home-pack-price">{pack.priceLabel}</div></div><div className="home-pack-meta"><span><Clock3 size={16} className="text-gold" /> {pack.durationLabel}</span><span><Images size={16} className="text-gold" /> {copy.delivery} {pack.deliveryLabel}</span></div><ul className="pack-features">{pack.details.map((detail) => <li key={detail}><CheckCircle2 size={16} className="text-teal" />{detail}</li>)}</ul><Link to={`/reservation?pack=${pack.id}`} className={`btn pack-cta ${pack.featured ? 'btn-primary' : 'btn-secondary'}`}>{copy.bookNow}</Link></Motion.article>)}</Motion.div></div></section>
    <section className="home-section home-portfolio py-section bg-dark overflow-hidden" aria-labelledby="portfolio-title"><div className="container"><div className="home-portfolio__layout"><Motion.div className="home-portfolio__copy" initial="initial" whileInView="animate" viewport={{ once: true }} variants={fadeIn}><p className="home-section-label text-gold">Portfolio</p><h2 id="portfolio-title">{copy.portfolioTitle}</h2><p>{copy.portfolioText}</p><Link to="/portfolio" className="btn btn-primary">{copy.viewGallery}<ArrowRight size={18} /></Link></Motion.div><div className="home-portfolio-grid">{previews.map((item, index) => <Motion.figure className={item.className} key={item.src} style={{ '--portfolio-image-position': item.objectPosition || 'center center' }} initial={{ opacity: 1, scale: 1 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} transition={{ duration: 0.6, delay: index * 0.15 }}><img src={item.srcSmall} srcSet={`${item.srcSmall} 480w, ${item.src} 1024w`} sizes="(max-width: 760px) 100vw, 33vw" width="480" height="480" alt={item.label} loading="lazy" decoding="async" /><figcaption className="glass-dark">{item.label}</figcaption></Motion.figure>)}</div></div></div></section>
    <section className="home-section home-testimonials py-section" aria-labelledby="testimonials-title"><div className="container"><Motion.div className="home-section-heading center" initial="initial" whileInView="animate" viewport={{ once: true }} variants={fadeIn}><p className="home-section-label">{copy.testimonialsLabel}</p><h2 id="testimonials-title">{copy.testimonialsTitle}</h2></Motion.div><Motion.div className="home-testimonial-grid" initial="initial" whileInView="animate" viewport={{ once: true }} variants={staggerContainer}>{copy.testimonials.map((testimonial) => <Motion.article className="testimonial-card glass" key={testimonial.name} variants={fadeIn}><div className="home-stars">{Array.from({ length: 5 }).map((_, index) => <Star key={index} size={16} fill="var(--c-gold)" stroke="none" />)}</div><p className="testimonial-quote">“{testimonial.quote}”</p><div className="testimonial-author"><div className="author-info"><strong>{testimonial.name}</strong><span>{testimonial.context}</span></div></div></Motion.article>)}</Motion.div></div></section>
    <section className="home-final-cta py-section bg-gold"><div className="container center"><Motion.div initial={{ opacity: 1, scale: 1 }} whileInView={{ opacity: 1, scale: 1 }} viewport={{ once: true }} className="cta-content"><Users size={48} className="cta-icon" /><h2>{copy.finalTitle}</h2><p>{copy.finalText}</p><Link to="/reservation" className="btn glass-dark btn-luxe">{copy.finalAction}</Link></Motion.div></div></section>
  </div>;
};

export default Home;
