server {
    if ($host = www.gsplus.vip) {
        return 301 https://gsplus.vip$request_uri;
    }

    server_name gsplus.vip www.gsplus.vip 178.105.50.226;

    root /var/www/goldenstudioplus/frontend/dist;
    index index.html;

    client_max_body_size 20M;

    location /api/ {
        proxy_pass http://127.0.0.1:4000/api/;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /uploads/ {
        alias /var/www/goldenstudioplus/uploads/;
        access_log off;
        expires 30d;
    }

    error_page 404 /404.html;

    location = /404.html {
        internal;
    }

    location / {
        try_files $uri.html $uri $uri/ =404;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/gsplus.vip/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/gsplus.vip/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot


}
server {
    if ($host = www.gsplus.vip) {
        return 301 https://gsplus.vip$request_uri;
    } # managed by Certbot


    if ($host = gsplus.vip) {
        return 301 https://gsplus.vip$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;

    server_name gsplus.vip www.gsplus.vip 178.105.50.226;
    return 404; # managed by Certbot




}