export const STATUS_LABELS = Object.freeze({
  PENDING_CONFIRMATION: 'En attente de confirmation',
  CONFIRMED: 'Confirmée',
  COMPLETED: 'Terminée',
  CANCELLED: 'Annulée',
  NO_SHOW: 'Client absent',
  REJECTED: 'Refusée',
  EXPIRED: 'Expirée',
  PENDING: 'En attente',
  NOT_REQUIRED: 'Non requise',
  SYNCING: 'Synchronisation en cours',
  RETRYING: 'Nouvelle tentative planifiée',
  PAYMENT_INFO_REQUIRED: 'Information de paiement requise',
  VERIFICATION_BLOCKED: 'Vérification temporairement bloquée',
  PROCESSING: 'Traitement en cours',
  VERIFIED: 'Vérifié',
  PAID: 'Payé',
  FAILED: 'Échec',
  REFUND_PENDING: 'Remboursement en attente',
  REFUNDED: 'Remboursé',
  NEW: 'Nouveau',
  IN_PROGRESS: 'En cours',
  WON: 'Gagné',
  LOST: 'Perdu',
  DRAFT: 'Brouillon',
  VALIDATED: 'Mentions validées',
  PUBLISHED: 'Publié',
  ARCHIVED: 'Archivé',
  ACTIVE: 'Actif',
  INACTIVE: 'Inactif',
  AVAILABLE: 'Disponible',
  ACCEPTED: 'Acceptée',
  SENT: 'Envoyé',
  SYNCED: 'Synchronisé',
  UPDATED: 'Mis à jour',
  DELETED: 'Supprimé',
  SKIPPED: 'Ignoré',
  OPEN: 'Ouvert',
  READ: 'Lu',
  CONTACT: 'Contact',
  B2B: 'Entreprise',
  QUOTE: 'Demande de devis',
  OWNER: 'Propriétaire',
  STAFF: 'Collaborateur',
  ADMIN: 'Administrateur',
  CUSTOMER: 'Client',
  STUDIO: 'Studio',
  SYSTEM: 'Système',
  OBSOLETE: 'Obsolète — ne pas renvoyer',
  DUPLICATE: 'Doublon',
  PERMANENTLY_FAILED: 'Échec définitif',
  ACTIONABLE_REVIEW_REQUIRED: 'Examen requis avant renvoi',
  REPLACED: 'Remplacée par une autre notification',
  UNCLASSIFIED: 'Non classée',
  AUCUN: 'Aucun',
  'AUCUN PAIEMENT': 'Aucun paiement',
});

export const PAYMENT_METHOD_LABELS = Object.freeze({ mtn_momo: 'MTN MoMo', orange_money: 'Orange Money' });

export const paymentMethodLabel = (method) => PAYMENT_METHOD_LABELS[String(method || '').trim()] || 'Mode non communiqué';

export const statusLabel = (status) => {
  const code = String(status || '').trim();
  if (!code) return '—';
  return STATUS_LABELS[code] || 'Statut non reconnu';
};
